BEGIN;

-- Only standalone manual cashbook vouchers may be edited. Entries generated by
-- customer debt, orders, returns or supplier workflows remain immutable and
-- continue to use their dedicated cancellation/reversal RPCs.
CREATE OR REPLACE FUNCTION public.rpc_update_manual_cashbook_transaction(
  p_cashbook_id text,
  p_input jsonb
) RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
DECLARE
  actor public.profiles%ROWTYPE;
  entry public.cashbook_transactions%ROWTYPE;
  next_method text := lower(COALESCE(NULLIF(p_input->>'method', ''), 'cash'));
  next_value numeric := round(COALESCE(NULLIF(p_input->>'value', '')::numeric, 0));
  next_date timestamptz;
BEGIN
  actor := public.require_authenticated_profile();
  IF actor.role NOT IN ('admin', 'accounting') THEN
    RAISE EXCEPTION '403: accounting role required' USING ERRCODE = '42501';
  END IF;

  SELECT * INTO STRICT entry
  FROM public.cashbook_transactions
  WHERE id = NULLIF(btrim(p_cashbook_id), '')
  FOR UPDATE;

  IF lower(COALESCE(entry.status, '')) NOT IN ('completed', 'paid')
     OR entry.cancelled_at IS NOT NULL THEN
    RAISE EXCEPTION 'Cancelled cashbook transactions cannot be edited';
  END IF;
  IF COALESCE(entry.transaction_type, '') NOT IN ('manual_thu', 'manual_chi')
     OR entry.customer_id IS NOT NULL
     OR entry.order_id IS NOT NULL
     OR entry.sales_return_id IS NOT NULL
     OR entry.supplier_id IS NOT NULL
     OR entry.purchase_id IS NOT NULL
     OR entry.purchase_payment_id IS NOT NULL
     OR entry.reversal_of_id IS NOT NULL THEN
    RAISE EXCEPTION 'Linked cashbook transactions must use their dedicated business workflow';
  END IF;
  IF next_value <= 0 THEN
    RAISE EXCEPTION 'Cashbook value must be positive';
  END IF;
  IF next_method NOT IN ('cash', 'bank', 'wallet') THEN
    RAISE EXCEPTION 'Cashbook method must be cash, bank or wallet';
  END IF;

  next_date := COALESCE(NULLIF(p_input->>'transactionDate', '')::timestamptz,
                        entry.transaction_date, entry.date, now());

  UPDATE public.cashbook_transactions
  SET date = next_date,
      transaction_date = next_date,
      category = COALESCE(NULLIF(btrim(p_input->>'category'), ''), 'Khác'),
      partner = COALESCE(NULLIF(btrim(p_input->>'partner'), ''), 'Khác'),
      value = next_value,
      method = next_method,
      payment_method = next_method,
      accounting = COALESCE((p_input->>'accounting')::boolean, true),
      note = COALESCE(p_input->>'note', ''),
      updated_by = actor.auth_user_id::text
  WHERE id = entry.id;

  INSERT INTO public.audit_logs(
    table_name, action, record_id, old_data, new_data, performed_by, created_at
  ) VALUES (
    'cashbook_transactions', 'UPDATE', entry.id, to_jsonb(entry),
    jsonb_build_object(
      'transaction_date', next_date,
      'category', COALESCE(NULLIF(btrim(p_input->>'category'), ''), 'Khác'),
      'partner', COALESCE(NULLIF(btrim(p_input->>'partner'), ''), 'Khác'),
      'value', next_value,
      'method', next_method,
      'accounting', COALESCE((p_input->>'accounting')::boolean, true),
      'note', COALESCE(p_input->>'note', '')
    ),
    actor.auth_user_id::text, now()
  );

  RETURN public.p2_cashbook_response(entry.id) || jsonb_build_object(
    'updated', true,
    'performed_by', actor.auth_user_id::text
  );
END;
$$;

REVOKE ALL ON FUNCTION public.rpc_update_manual_cashbook_transaction(text, jsonb)
  FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.rpc_update_manual_cashbook_transaction(text, jsonb)
  TO authenticated;

INSERT INTO public.schema_migrations(version, description)
VALUES ('0030', 'Audited editing for standalone manual cashbook transactions')
ON CONFLICT (version) DO NOTHING;

COMMIT;
